#cloud-config
autoinstall:
  version: 1

  # Benutzer soll beim Setup interaktiv gesetzt werden
  interactive-sections:
    - user-data

  storage:
    layout:
      name: direct

  user-data:
    disable_root: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC4wGFQtP60UQDmmPzvCaLjEXG98iPBIkelnjVgGifkA